mindmap
  root((Empathie))
    Client
      Dit
        Je veux réserver un service en quelques clics.
        Je veux lire les avis avant de choisir un prestataire.
      Fait
        Cherche sur Google ou réseaux sociaux.
        Compare plusieurs offres.
      Pense
        Est-ce que ce service est fiable ?
        J’espère que l’employé arrivera à l’heure.
      Ressent
        Stressée si le service est mal fait ou en retard.
        Satisfaite si tout est simple et efficace.
    
    Employé
      Dit
        Je veux plus de clients.
        Je veux être payé rapidement.
      Fait
        Propose ses services sur des plateformes.
        Gère son planning avec WhatsApp ou un agenda.
      Pense
        J’espère que le client ne va pas annuler.
        Est-ce que je vais être bien noté ?
      Ressent
        Frustré quand un client est mécontent sans raison.
        Fier quand il reçoit de bons avis.
